### PR TITLE
Use 2 "tricks" to speed up Theano version.

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by moorepants** [comment]
Cool, thanks!

**Comment by moorepants** [comment]
Why does changing this matter?:

``` python
#inp = np.random.random(len(arguments))
inp = [np.asarray(x) for x in np.random.random(len(arguments))]
```

I need to do it below for the np.hstack line in the right_hand_side function too.

**Comment by nouiz** [comment]
np.random.random(len(arguments)) is a numpy.ndarray of 1 dimensions.
when you do a_function(*a_ndarray_vector)
this create a tuple of numpy scalar, that is passed as input to the function.

numpy scalar are different object then numpy.ndarray, even when numpy.ndarray have 0 dimensions. theano_function() create a theano function that expect numpy.ndarray as inputs, not numpy.scalar. There is good reason for that, but in short, Theano have a better support for numpy.ndarray then numpy scalar.

So to make a "fair" comparison, you need to move out the cast outside of the timming of Theano. This is particulary important as this add much overhead to Theano due to a weakness in Theano in that case.

**Comment by moorepants** [comment]
Thanks.

**Pull request merged**
