### PR TITLE
Cross platform

### PR DESCRIPTION
**Pull request by moorepants**
If anyone has a mac or windows, could you see if the tests pass?

@PythonDynamics/owners

### CODE REVIEW

**Comment by moorepants** [comment]
Weird, test coverage now says 18% on travis, and it was at 96% before. And on my machine it says 80%. Not sure what the discrepancy is.

**Comment by moorepants** [comment]
duh, forgot to make it a class

**Comment by chrisdembia** [comment]
I'll try this at some point for mac. Not sure when. You might need to bug
me about it.

**Comment by moorepants** [comment]
@chrisdembia Ok. I'm bugging you :)

**Comment by gilbertgede** [comment]
I just tried it on my mac, but it is not working. Not sure if the issue is with my machine though. I'll keep looking into it.

**Comment by gilbertgede** [comment]
I should clarify that I'm using Python3.3

**Comment by moorepants** [comment]
This has not been tested on Python 3. I don't use python 3 personally because there are still important packages that I use that haven't been ported. So python 3 is still an after thought for me. But this package should run on python 3, as there are no dependencies that don't have python 3 versions. Travis currently only tests python 2.7.

**Comment by moorepants** [comment]
Btw, I am only planning to get the working cross platform for anaconda 1.8 with python 2.7 for the tutorial. Anything beyond that is icing on the cake. Of course, we should get it working on everything in the future.

**Comment by moorepants** [comment]
Actually, I'm not sure that Theano 0.6.0 works on Python 3 yet, which is a dependency for running the tests.

**Comment by moorepants** [comment]
Looks like Theano 0.6.0 should run with python 3.3: https://pypi.python.org/pypi/Theano

There is a bunch of instructions for installing in on a mac in their docs.

**Comment by moorepants** [comment]
This fails on Windows XP 32 bit + Anaconda 1.8 for Cython. May be because I don't have a compiler? Or this: https://github.com/cython/cython/wiki/InstallingOnWindows#mingw--numpy--pyximport-at-runtime

I get the `Unable to find vcvarsall.bat` error.

I haven't been able to get the latest theano installed either.

**Comment by moorepants** [comment]
Actually, I wasn't testing this branch. Need to install git or something...

**Comment by moorepants** [comment]
Ok, I got the Cython file to build if I run it in the Git Bash (Ming3W2). It creates a `.pyd` file that is importable. But if I run:

`python multibody_system_setup.py build_ext --inplace`` in the normal Windows CMD prompt, it seems to just hang. So maybe Mingw32 provides the compiler it needs. I'm not sure Anaconda alone does.

**Comment by moorepants** [comment]
This could be relevant: http://stackoverflow.com/a/16740123/467314

**Comment by moorepants** [comment]
Maye I just need to install Visual Studio: http://stackoverflow.com/questions/13038591/cant-compile-cython-code-unrecognized-command-line-option-mno-cygwin

**Comment by moorepants** [comment]
Anaconda comes with MingW32 and the mutlibody_system.c will compile with distutils with a "new" cmd prompt window. I'm not sure why it hangs otherwise. Maybe because of the use of sub process?

**Comment by moorepants** [comment]
I'm going to merge this. It doesn't make things worse, i.e. things don't really work for Cython on Windows perfectly yet. I sorta got things to work on Windows, but I think it is a different issue, namely something in the `python setup.py build_ext` call.

**Pull request merged**
