### PR TITLE
Cython class

### PR DESCRIPTION
**Pull request by moorepants**
The Cython generator is a very procedural but if I segmented the Cython generator into a bunch of small functions then I'd be passing around a bunch of arguments to each function. So I wrote this in a class form. It definitely organizes things better. What do you all think?

@PythonDynamics

### CODE REVIEW

**Comment by chrisdembia** [comment]
- This may not be the best place to make this comment, but is the Cython generator expected to be cross-platform? It expects the shared library file name extension to be '.so', while on Windows it would be '.dll'.
  https://github.com/PythonDynamics/pydy-code-gen/blob/cython-class/pydy_code_gen/code.py#L360
- Do you think it would be a natural progression for the other generators to become classes as well? I don't understand this code well enough, but would it make sense to eventually move to a structure where there's a Generator superclass, and there's a few subclasses of it (Cython, Theano, etc.), and the superclass requires the subclasses to have a numeric_right_hand_side method that does what the current method does? Then, for convenience, there could be a non-class numeric_right_hand_side method that invokes the proper subclass.

**Comment by moorepants** [comment]
- Yes, we'd want it to be cross platform. I'd need to test out Cython on Windows and Mac to figure that out. Travis CI offers Mac testing now, so we could set that up. I could try to create a Windows XP (only Windows I own) Vagrant box that I could test this locally with, but it isn't my priority.
- Yes, the best would be to have a general generator class and to sub-class for each method 'python', 'lambdify', 'theano', 'numba', 'parakeet', etc. Right now the lambdify and theano codes require little code so I didn't write classes for them and I haven't really identified the commonalities between the three current methods. 'lambdify' and 'theano' work basically the same, but 'cython' is completely different. I could generate a 'python', 'octave', and 'matlab' file that would be similar to cython and then make the common class structure. So the answer, is yes it needs to be organized in that fashion, but right now I'm just exploring the possibilities and don't have a super clear idea on what will work and how to organize everything. Suggestions are welcome.

Also, I don't really like `numeric_right_hand_side` or `rhs` or `right_hand_side` as names, as you've pointed out before. Any suggestions on how to name this clearly is welcome too.

**Comment by moorepants** [comment]
About Windows. Distutils and Cython should generate the correct shared library extension. There is nothing in my code that forces '.so' or '.dll', so I think it would work.

**Comment by moorepants** [comment]
I take that back. The line you point to looks for a shared library files so that it can import it if already generated. I need to make that cross platform.

**Comment by moorepants** [comment]
I'm going to merge this into master. It is essentially the same thing, just refactored into a class. I'm working on a better class organization that is more general but it will take some more thinking.

**Pull request merged**
